apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-api.fullname" . }}-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secretEnv.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secretEnv.POSTGRES_PASSWORD | quote }}
